# Generated by Django 2.0.4 on 2018-04-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datatable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('someAttr1', models.CharField(max_length=30)),
                ('someAttr2', models.CharField(max_length=30)),
                ('someAttr3', models.CharField(max_length=30)),
                ('someAttr4', models.CharField(max_length=30)),
                ('someAttr5', models.CharField(max_length=30)),
                ('someAttr6', models.CharField(max_length=30)),
                ('someAttr7', models.CharField(max_length=30)),
                ('someAttr8', models.CharField(max_length=30)),
                ('someAttr9', models.CharField(max_length=30)),
                ('someAttr10', models.CharField(max_length=30)),
                ('someAttr11', models.CharField(max_length=30)),
            ],
        ),
    ]
